<a href="https://colab.research.google.com/github/cmdshati/AI_Resolution/blob/main/Day_04_DataPreProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data PreProcessing : 1. Data cleaning (Handle Missing Values, Remove Dupliacy, Fix inconsistent Formatting)

# 2. DaTa Transformation :  Feature Selection : Select important feature , derive feature from existing features(like Fisrt name + Last Name = FullName), Encoding Categorical Variables ( Conver text to number like convert  yes no in label 1 or 0 ), Scaling or Normalization

In [ ]:
# Data PreProcessing
import pandas as  pd

data = {"Name": ["Anna", "Mike", "Sarah","Zarah", "John"],
        "Age":[28,"nan",67,56,"nan"],
        "Salary":[6000,70000, "nan", 56000,45000]}
data = pd.DataFrame(data)
data

    Name  Age Salary
0   Anna   28   6000
1   Mike  nan  70000
2  Sarah   67    nan
3  Zarah   56  56000
4   John  nan  45000

In [ ]:

import pandas as  pd
import numpy as np


data = {"Name": ["Anna", "Mike", "Sarah","Zarah", "John"],
        "Age":[28,np.nan,67,56,np.nan],
        "Salary":[6000,70000, np.nan, 56000,45000]}
data = pd.DataFrame(data)
data

    Name   Age   Salary
0   Anna  28.0   6000.0
1   Mike   NaN  70000.0
2  Sarah  67.0      NaN
3  Zarah  56.0  56000.0
4   John   NaN  45000.0

# Nan means Not  a Number . Used to represent missing number , uuncomputable number .

In [ ]:
import pandas as  pd
import numpy as np


data = {"Name": ["Anna", "Mike", "Sarah","Zarah", "John"],
        "Age":[28,np.nan,67,56,np.nan],
        "Salary":[6000,70000, np.nan, 56000,45000]}
df = pd.DataFrame(data)
df

# how to find missing values
df.isnull().sum()

Name      0
Age       2
Salary    1
dtype: int64

# Handle Missing Value : Method 1 ( Remove Missing Values)

In [ ]:
df_drop =df.dropna()
df_drop

    Name   Age   Salary
0   Anna  28.0   6000.0
3  Zarah  56.0  56000.0

# Method 2 Fill with a constant value

In [ ]:
df_fill =df.fillna("Unknown")
df_fill

    Name      Age   Salary
0   Anna     28.0   6000.0
1   Mike  Unknown  70000.0
2  Sarah     67.0  Unknown
3  Zarah     56.0  56000.0
4   John  Unknown  45000.0

In [ ]:
df_fill =df.fillna(0)
df_fill

    Name   Age   Salary
0   Anna  28.0   6000.0
1   Mike   0.0  70000.0
2  Sarah  67.0      0.0
3  Zarah  56.0  56000.0
4   John   0.0  45000.0

# Method 3 - Fill with a Statistical value like mean or median

In [ ]:
df_stat = df.copy()
df_stat['Age'] = df_stat['Age'].fillna(df_stat['Age'].mean())
df_stat['Salary'] = df_stat['Salary'].fillna(df_stat['Salary'].median())
df_stat

    Name        Age   Salary
0   Anna  28.000000   6000.0
1   Mike  50.333333  70000.0
2  Sarah  67.000000  50500.0
3  Zarah  56.000000  56000.0
4   John  50.333333  45000.0

In [ ]:
df_stat = df.copy()
df_stat['Age'] = df_stat['Age'].fillna(df_stat['Age'].mean())
df_stat['Salary'] = df_stat['Salary'].fillna(df_stat['Salary'].median())
df_stat

    Name        Age   Salary
0   Anna  28.000000   6000.0
1   Mike  50.333333  70000.0
2  Sarah  67.000000  50500.0
3  Zarah  56.000000  56000.0
4   John  50.333333  45000.0

# Method 4 : Fill with a Forward value also known as Forward Fill

In [ ]:
df_ffill = df.copy()
df_ffill['Age'] = df_ffill['Age'].fillna(method='ffill')
df_ffill['Salary'] = df_ffill['Salary'].fillna(method='ffill')
df_ffill

/tmp/ipykernel_760/1007069161.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill['Age'] = df_ffill['Age'].fillna(method='ffill')
/tmp/ipykernel_760/1007069161.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill['Salary'] = df_ffill['Salary'].fillna(method='ffill')

    Name   Age   Salary
0   Anna  28.0   6000.0
1   Mike  28.0  70000.0
2  Sarah  67.0  70000.0
3  Zarah  56.0  56000.0
4   John  56.0  45000.0

In [ ]:
df_ffill= df.fillna(method='ffill')
df_ffill

/tmp/ipykernel_760/188444996.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill= df.fillna(method='ffill')

    Name   Age   Salary
0   Anna  28.0   6000.0
1   Mike  28.0  70000.0
2  Sarah  67.0  70000.0
3  Zarah  56.0  56000.0
4   John  56.0  45000.0

# Method 5 Fill with a backward value  Backward Fill

In [ ]:
df_bfill = df.copy()
df_bfill['Age'] = df_bfill['Age'].fillna(method='bfill')
df_bfill['Salary'] = df_bfill['Salary'].fillna(method='bfill')
df_bfill

/tmp/ipykernel_760/3470515838.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill['Age'] = df_bfill['Age'].fillna(method='bfill')
/tmp/ipykernel_760/3470515838.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill['Salary'] = df_bfill['Salary'].fillna(method='bfill')

    Name   Age   Salary
0   Anna  28.0   6000.0
1   Mike  67.0  70000.0
2  Sarah  67.0  56000.0
3  Zarah  56.0  56000.0
4   John   NaN  45000.0

In [ ]:
df_bfill= df.fillna(method='bfill')
df_bfill

/tmp/ipykernel_760/4225294997.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill= df.fillna(method='bfill')

    Name   Age   Salary
0   Anna  28.0   6000.0
1   Mike  67.0  70000.0
2  Sarah  67.0  56000.0
3  Zarah  56.0  56000.0
4   John   NaN  45000.0

# Method 6 Interpolation

In [ ]:
df_interpol = df.copy()
df_interpol['Age'] = df_interpol['Age'].interpolate()
df_interpol['Salary'] = df_interpol['Salary'].interpolate()
df_interpol

    Name   Age   Salary
0   Anna  28.0   6000.0
1   Mike  47.5  70000.0
2  Sarah  67.0  63000.0
3  Zarah  56.0  56000.0
4   John  56.0  45000.0

In [ ]:
df_interpol= df.interpolate()
df_interpol

/tmp/ipykernel_760/26760258.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpol= df.interpolate()

    Name   Age   Salary
0   Anna  28.0   6000.0
1   Mike  47.5  70000.0
2  Sarah  67.0  63000.0
3  Zarah  56.0  56000.0
4   John  56.0  45000.0

In [ ]:
df

    Name   Age   Salary
0   Anna  28.0   6000.0
1   Mike   NaN  70000.0
2  Sarah  67.0      NaN
3  Zarah  56.0  56000.0
4   John   NaN  45000.0

# Duplicate Values

In [ ]:
data = {"Name": ["Anna", "Mike", "Sarah","Zarah", "Anna"],
        "Age":[28,56,67,56,28],
        "City":["Dhaka","CTG", "Rajshahi", "Jashore","Dhaka"]}
df = pd.DataFrame(data)
df

    Name  Age      City
0   Anna   28     Dhaka
1   Mike   56       CTG
2  Sarah   67  Rajshahi
3  Zarah   56   Jashore
4   Anna   28     Dhaka

# Detect Duplicate

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

# Method 1 Remove all Dupliacte Rows

In [ ]:
df_drop = df.drop_duplicates()
df_drop

    Name  Age      City
0   Anna   28     Dhaka
1   Mike   56       CTG
2  Sarah   67  Rajshahi
3  Zarah   56   Jashore

# Method 2 Keep last Occurance Instead of First

In [ ]:
df_drop = df.drop_duplicates(keep='last')
df_drop

    Name  Age      City
1   Mike   56       CTG
2  Sarah   67  Rajshahi
3  Zarah   56   Jashore
4   Anna   28     Dhaka

# Method 3 Marks dupliacte without Removing

In [ ]:
df_duplicate = df.copy()
df["duplicate"] = df.duplicated(keep=False)
df["duplicate"]

0     True
1    False
2    False
3    False
4     True
Name: duplicate, dtype: bool

# Data Transformation : Pivot Table

In [ ]:
data = {"Name": ["Anna", "Mike", "Sarah","Zarah", "Alex"],
        "Department":["HR","IT","HR","IT","HR"],
        "Gender":["Female","Male","Female","Female","Male"],
        "Marks":[80, 75, 89, 67, 90]}

# convert  it inoto dataframe
df = pd.DataFrame(data)
df

    Name Department  Gender  Marks
0   Anna         HR  Female     80
1   Mike         IT    Male     75
2  Sarah         HR  Female     89
3  Zarah         IT  Female     67
4   Alex         HR    Male     90

# To show marks in departmentwise  accroding to gender . Use Pivot table for that.

In [ ]:
pivotTable = df.pivot_table(index='Department', columns='Gender', values='Marks', aggfunc='mean')
pivotTable

Gender      Female  Male
Department
HR            84.5  90.0
IT            67.0  75.0

In [ ]:
pivotTable = df.pivot_table(index='Department', columns='Gender', values='Marks', aggfunc='sum')
pivotTable

Gender      Female  Male
Department
HR             169    90
IT              67    75