<a href="https://colab.research.google.com/github/cmdshati/AI_Resolution/blob/main/Day_03_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
fruits = ["apple", "Banana", "Mango", "Lichi", "Orange"]
series = pd.Series(fruits)
series

0     apple
1    Banana
2     Mango
3     Lichi
4    Orange
dtype: object

# Pandas  Data structure two type : Series and DataFrame
# Series : One dimensional array (like a single column )

In [21]:
import pandas as pd
fruits = ["apple", "Banana", "Mango", "Lichi", "Orange"]
series = pd.Series(fruits,index=[1,2,3,4,5], name = "Fruits")
series

1     apple
2    Banana
3     Mango
4     Lichi
5    Orange
Name: Fruits, dtype: object

# DataFrame = Two dimensional Data array

In [17]:
data = {"Fruit": ["apple", "mango", "lichi", "Orange"], "Quantity":[20, 39, 60, 67], "Price":[400, 500, 600, 800]}
# data
print(data)

{'Fruit': ['apple', 'mango', 'lichi', 'Orange'], 'Quantity': [20, 39, 60, 67], 'Price': [400, 500, 600, 800]}

In [12]:
# Dictionary with list  ...show as dataframe
data = {"Fruit": ["apple", "mango", "lichi", "Orange"], "Quantity":[20, 39, 60, 67], "Price":[400, 500, 600, 800]}
df= pd.DataFrame(data)
print(df)

    Fruit  Quantity  Price
0   apple        20    400
1   mango        39    500
2   lichi        60    600
3  Orange        67    800

In [148]:
# Dictionary with list  ...show as dataframe
data = {"Fruit": ["apple", "mango", "lichi", "Orange"], "Quantity":[20, 39, 60, 67], "Price":[400, 500, 600, 800]}
df = pd.DataFrame(data,index=[1,2,3,4])
df

    Fruit  Quantity  Price
1   apple        20    400
2   mango        39    500
3   lichi        60    600
4  Orange        67    800

In [149]:
df.head()

    Fruit  Quantity  Price
1   apple        20    400
2   mango        39    500
3   lichi        60    600
4  Orange        67    800

In [150]:
df.tail()

    Fruit  Quantity  Price
1   apple        20    400
2   mango        39    500
3   lichi        60    600
4  Orange        67    800

In [151]:
df.head(3)

   Fruit  Quantity  Price
1  apple        20    400
2  mango        39    500
3  lichi        60    600

In [152]:
df.tail(3)

    Fruit  Quantity  Price
2   mango        39    500
3   lichi        60    600
4  Orange        67    800

In [153]:
df.shape

(4, 3)

# df.describe() =  to show stastics of data like count , mean, max, standard deviation

In [154]:
df.describe()

        Quantity       Price
count   4.000000    4.000000
mean   46.500000  575.000000
std    21.299452  170.782513
min    20.000000  400.000000
25%    34.250000  475.000000
50%    49.500000  550.000000
75%    61.750000  650.000000
max    67.000000  800.000000

# df.info() = summary of data such as data types, non null values

In [155]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 1 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Fruit     4 non-null      object
 1   Quantity  4 non-null      int64
 2   Price     4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 128.0+ bytes

In [156]:
df.dtypes

Fruit       object
Quantity     int64
Price        int64
dtype: object

# df.columns = to show column

In [157]:
df.columns

Index(['Fruit', 'Quantity', 'Price'], dtype='object')

# Viewing and selecting data

In [158]:
df['Fruit']

1     apple
2     mango
3     lichi
4    Orange
Name: Fruit, dtype: object

In [159]:
df["Quantity"]

1    20
2    39
3    60
4    67
Name: Quantity, dtype: int64

# To show multiple columns

In [160]:
df[['Fruit','Quantity']]

    Fruit  Quantity
1   apple        20
2   mango        39
3   lichi        60
4  Orange        67

In [161]:
df[['Fruit','Quantity','Price']]

    Fruit  Quantity  Price
1   apple        20    400
2   mango        39    500
3   lichi        60    600
4  Orange        67    800

# Loc and iloc

In [162]:
df.loc[1]

Fruit       apple
Quantity       20
Price         400
Name: 1, dtype: object

In [163]:
df.loc[[1,2]]

   Fruit  Quantity  Price
1  apple        20    400
2  mango        39    500

In [164]:
df.loc[[1,3]]

   Fruit  Quantity  Price
1  apple        20    400
3  lichi        60    600

In [165]:
df.loc[[1,3], "Quantity"]

1    20
3    60
Name: Quantity, dtype: int64

In [166]:
df.loc[[1,3], ["Quantity"]]

   Quantity
1        20
3        60

In [167]:
df.loc[[1,3], ["Quantity", "Price"]]

   Quantity  Price
1        20    400
3        60    600

In [168]:
df.iloc[0]

Fruit       apple
Quantity       20
Price         400
Name: 1, dtype: object

In [169]:
df.iloc[0,2]

np.int64(400)

In [170]:
df.iloc[1,2]

np.int64(500)

# Typecasting in data Frame

In [171]:
df['Price']

1    400
2    500
3    600
4    800
Name: Price, dtype: int64

In [172]:
df['Price'].dtypes

dtype('int64')

In [173]:
df['Price'] = df['Price'].astype("float")
df['Price'].dtypes

dtype('float64')

In [174]:
df.dtypes

Fruit        object
Quantity      int64
Price       float64
dtype: object

# Sorting

In [175]:
df.sort_values(by="Quantity")

    Fruit  Quantity  Price
1   apple        20  400.0
2   mango        39  500.0
3   lichi        60  600.0
4  Orange        67  800.0

In [177]:
df.sort_values(by="Price", ascending=True)

    Fruit  Quantity  Price
1   apple        20  400.0
2   mango        39  500.0
3   lichi        60  600.0
4  Orange        67  800.0

# Sorting by index

In [180]:
df.sort_index()

    Fruit  Quantity  Price
1   apple        20  400.0
2   mango        39  500.0
3   lichi        60  600.0
4  Orange        67  800.0

In [181]:
df.sort_index(ascending=False)

    Fruit  Quantity  Price
4  Orange        67  800.0
3   lichi        60  600.0
2   mango        39  500.0
1   apple        20  400.0

Renaming Column Names

In [183]:
df.rename(columns={"Fruit":"FRUITS"})
df = df.rename(columns={"Fruit":"FRUITS", "Quantity":"QUANTITY", "Price":"PRICE"})
df

   FRUITS  QUANTITY  PRICE
1   apple        20  400.0
2   mango        39  500.0
3   lichi        60  600.0
4  Orange        67  800.0

Column Drop or Remove a specific column

In [184]:
df1 = df.drop(columns=["PRICE"])

df1

   FRUITS  QUANTITY
1   apple        20
2   mango        39
3   lichi        60
4  Orange        67

In [186]:
df2 = df.drop(columns=["QUANTITY"])
df2

   FRUITS  PRICE
1   apple  400.0
2   mango  500.0
3   lichi  600.0
4  Orange  800.0

In [187]:
df2 = df.drop(columns=["QUANTITY", "PRICE"])
df2

   FRUITS
1   apple
2   mango
3   lichi
4  Orange

In [188]:
df

   FRUITS  QUANTITY  PRICE
1   apple        20  400.0
2   mango        39  500.0
3   lichi        60  600.0
4  Orange        67  800.0

# droping by row

In [189]:
df.drop(index=1)

   FRUITS  QUANTITY  PRICE
2   mango        39  500.0
3   lichi        60  600.0
4  Orange        67  800.0

In [190]:
df

   FRUITS  QUANTITY  PRICE
1   apple        20  400.0
2   mango        39  500.0
3   lichi        60  600.0
4  Orange        67  800.0

# Combining Two Dataset

In [191]:
DataFrame1 = pd.DataFrame({"Fruit": ["apple", "mango", "lichi", "Orange"], "Quantity":[20, 39, 60, 67], "Price":[400, 500, 600, 800]})
DataFrame1

    Fruit  Quantity  Price
0   apple        20    400
1   mango        39    500
2   lichi        60    600
3  Orange        67    800

In [192]:
DataFrame2 = pd.DataFrame({"Fruit": ["apple", "Papaya", "Guava", "Orange"], "Quantity":[20, 39, 60, 67], "Price":[400, 500, 600, 800]})
DataFrame2

    Fruit  Quantity  Price
0   apple        20    400
1  Papaya        39    500
2   Guava        60    600
3  Orange        67    800

In [193]:
mergedf = pd.merge(DataFrame1, DataFrame2, on="Fruit")
mergedf

    Fruit  Quantity_x  Price_x  Quantity_y  Price_y
0   apple          20      400          20      400
1  Orange          67      800          67      800

In [194]:
mergedf = pd.merge(DataFrame1, DataFrame2, on="Fruit", how="right")
mergedf

    Fruit  Quantity_x  Price_x  Quantity_y  Price_y
0   apple        20.0    400.0          20      400
1  Papaya         NaN      NaN          39      500
2   Guava         NaN      NaN          60      600
3  Orange        67.0    800.0          67      800

In [195]:
mergedf = pd.merge(DataFrame1, DataFrame2, on="Fruit", how="left")
mergedf

    Fruit  Quantity_x  Price_x  Quantity_y  Price_y
0   apple          20      400        20.0    400.0
1   mango          39      500         NaN      NaN
2   lichi          60      600         NaN      NaN
3  Orange          67      800        67.0    800.0

In [196]:
mergedf = pd.merge(DataFrame1, DataFrame2, on="Fruit", how="outer")
mergedf

    Fruit  Quantity_x  Price_x  Quantity_y  Price_y
0   Guava         NaN      NaN        60.0    600.0
1  Orange        67.0    800.0        67.0    800.0
2  Papaya         NaN      NaN        39.0    500.0
3   apple        20.0    400.0        20.0    400.0
4   lichi        60.0    600.0         NaN      NaN
5   mango        39.0    500.0         NaN      NaN

Concat two data set

In [197]:
dfconcat= pd.concat([DataFrame1, DataFrame2])
dfconcat

    Fruit  Quantity  Price
0   apple        20    400
1   mango        39    500
2   lichi        60    600
3  Orange        67    800
0   apple        20    400
1  Papaya        39    500
2   Guava        60    600
3  Orange        67    800

In [198]:
dfconcatRow= pd.concat([DataFrame1, DataFrame2],ignore_index=True,axis=0)
# axis 0  means row wise concat
dfconcatRow

    Fruit  Quantity  Price
0   apple        20    400
1   mango        39    500
2   lichi        60    600
3  Orange        67    800
4   apple        20    400
5  Papaya        39    500
6   Guava        60    600
7  Orange        67    800

In [199]:
dfconcatColumn= pd.concat([DataFrame1, DataFrame2],ignore_index=True,axis=1)
# axis 1 means comulumn wise concat
dfconcatColumn

        0   1    2       3   4    5
0   apple  20  400   apple  20  400
1   mango  39  500  Papaya  39  500
2   lichi  60  600   Guava  60  600
3  Orange  67  800  Orange  67  800

# Adding new Column in the concat Dataset

In [201]:
newData = {"Discount":[2, 6, 8, 9, 6, 9,3]}
# conver into DataFrame
Discount = pd.DataFrame(newData)
Discount

   Discount
0         2
1         6
2         8
3         9
4         6
5         9
6         3

In [202]:
newDataSet= pd.concat([dfconcatRow,Discount],axis=1)
newDataSet

    Fruit  Quantity  Price  Discount
0   apple        20    400       2.0
1   mango        39    500       6.0
2   lichi        60    600       8.0
3  Orange        67    800       9.0
4   apple        20    400       6.0
5  Papaya        39    500       9.0
6   Guava        60    600       3.0
7  Orange        67    800       NaN